#hibernate.datasource.url=jdbc:postgresql://localhost:5432/postgres
#hibernate.datasource.username=postgres
#hibernate.datasource.password=1304
#hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#hibernate.show_sql=false
#hibernate.hbm2ddl.auto=none