AutoServiceConfig.allowAddGaragePlace=true
AutoServiceConfig.allowDeleteGaragePlaces=true
AutoServiceConfig.allowShiftOrdersTime=true
AutoServiceConfig.allowDeleteOrder=true
hibernate.datasource.url=jdbc:postgresql://localhost:5432/autoservice_db
hibernate.datasource.username=postgres
hibernate.datasource.password=1304
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=false
hibernate.hbm2ddl.auto=none
jwt.secret.key=LGJe1DWoi8OjWUh1FzqmtAfyPIXdBxW2E3IITUWv94a