-- liquibase formatted sql

-- changeset fedor:1775580965579-1
CREATE SEQUENCE IF NOT EXISTS brands_id_seq START WITH 1 INCREMENT BY 1;

-- changeset fedor:1775580965579-2
CREATE SEQUENCE IF NOT EXISTS price_history_id_seq START WITH 1 INCREMENT BY 1;

-- changeset fedor:1775580965579-3
CREATE SEQUENCE IF NOT EXISTS product_categories_id_seq START WITH 1 INCREMENT BY 1;

-- changeset fedor:1775580965579-4
CREATE SEQUENCE IF NOT EXISTS product_prices_id_seq START WITH 1 INCREMENT BY 1;

-- changeset fedor:1775580965579-5
CREATE SEQUENCE IF NOT EXISTS products_id_seq START WITH 1 INCREMENT BY 1;

-- changeset fedor:1775580965579-6
CREATE SEQUENCE IF NOT EXISTS shops_id_seq START WITH 1 INCREMENT BY 1;

-- changeset fedor:1775580965579-7
CREATE TABLE brands
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(25)                              NOT NULL,
    country        VARCHAR(50)                              NOT NULL,
    logo_image_url VARCHAR                                  NOT NULL,
    CONSTRAINT brands_pkey PRIMARY KEY (id)
);

-- changeset fedor:1775580965579-8
CREATE TABLE price_history
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id  INTEGER                                  NOT NULL,
    shop_id     INTEGER                                  NOT NULL,
    old_price   numeric,
    new_price   numeric                                  NOT NULL,
    change_date date                                     NOT NULL,
    CONSTRAINT price_history_pkey PRIMARY KEY (id)
);

-- changeset fedor:1775580965579-9
CREATE TABLE product_categories
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(25)                              NOT NULL,
    description VARCHAR(50)                              NOT NULL,
    image_url   VARCHAR                                  NOT NULL,
    CONSTRAINT product_categories_pkey PRIMARY KEY (id)
);

-- changeset fedor:1775580965579-10
CREATE TABLE product_prices
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id       INTEGER                                  NOT NULL,
    shop_id          INTEGER                                  NOT NULL,
    price            numeric                                  NOT NULL,
    start_date       date                                     NOT NULL,
    discount_percent INTEGER                                  NOT NULL,
    status           VARCHAR(25)                              NOT NULL,
    CONSTRAINT product_prices_pkey PRIMARY KEY (id)
);

-- changeset fedor:1775580965579-11
CREATE TABLE products
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(50)                              NOT NULL,
    description VARCHAR(50)                              NOT NULL,
    amount      numeric                                  NOT NULL,
    unit        VARCHAR(10)                              NOT NULL,
    brand_id    INTEGER                                  NOT NULL,
    category_id INTEGER                                  NOT NULL,
    image_url   VARCHAR                                  NOT NULL,
    CONSTRAINT products_pkey PRIMARY KEY (id)
);

-- changeset fedor:1775580965579-12
CREATE TABLE shops
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(25)                              NOT NULL,
    city           VARCHAR(25)                              NOT NULL,
    address        VARCHAR(50)                              NOT NULL,
    logo_image_url VARCHAR                                  NOT NULL,
    CONSTRAINT shops_pkey PRIMARY KEY (id)
);

-- changeset fedor:1775580965579-13
ALTER TABLE brands
    ADD CONSTRAINT brands_name_key UNIQUE (name);

-- changeset fedor:1775580965579-14
ALTER TABLE product_categories
    ADD CONSTRAINT product_categories_name_key UNIQUE (name);

-- changeset fedor:1775580965579-15
ALTER TABLE price_history
    ADD CONSTRAINT fk_price_history_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE NO ACTION;

-- changeset fedor:1775580965579-16
ALTER TABLE price_history
    ADD CONSTRAINT fk_price_history_shop_id FOREIGN KEY (shop_id) REFERENCES shops (id) ON DELETE NO ACTION;

-- changeset fedor:1775580965579-17
ALTER TABLE products
    ADD CONSTRAINT fk_product_brand_id FOREIGN KEY (brand_id) REFERENCES brands (id) ON DELETE NO ACTION;

-- changeset fedor:1775580965579-18
ALTER TABLE products
    ADD CONSTRAINT fk_product_category_id FOREIGN KEY (category_id) REFERENCES product_categories (id) ON DELETE NO ACTION;

-- changeset fedor:1775580965579-19
ALTER TABLE product_prices
    ADD CONSTRAINT fk_product_price_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE NO ACTION;

-- changeset fedor:1775580965579-20
ALTER TABLE product_prices
    ADD CONSTRAINT fk_product_price_shop_id FOREIGN KEY (shop_id) REFERENCES shops (id) ON DELETE NO ACTION;

