spring.application.name=ProductService
spring.datasource.url=jdbc:postgresql://localhost:5432/productService_db
spring.datasource.username=postgres
spring.datasource.password=1304
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:liquibase/db.changelog-master.xml
