spring.application.name=ProductService
spring.datasource.url=jdbc:postgresql://localhost:5432/productService_db
spring.datasource.username=postgres
spring.datasource.password=1304
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:liquibase/db.changelog-master.xml
yandex.cloud.key.id=YCAJELjjqTgLhLTTyV0YF1n_V
yandex.cloud.secret.key=YCM5fr6n3NahecvwJzfNcfP11I2FEk5ojFTXsEaA
yandex.cloud.region=ru-central1-a
s3.endpoint=https://storage.yandexcloud.net
yandex.cloud.bucket.name=bucket-for-final-task
