spring.application.name=UserService
server.port=8082
server.servlet.context-path=/api/user-service
spring.datasource.url=jdbc:postgresql://localhost:5432/userService_db
spring.datasource.username=postgres
spring.datasource.password=1304
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:liquibase/db.changelog-master.xml
jwt.secret.access=ZgDkMSJhYTSkT2rfSfryr7yAK9mNi1AGmd5hSgEXBvW
jwt.secret.refresh=U2FqCBetemUyDbOLwpCXtUGcva6OhrzIgBQLvJvh2JA