spring.application.name=NotificationService
server.port=8083
server.servlet.context-path=/api/notification-service
spring.datasource.url=jdbc:postgresql://localhost:5432/notificationService_db
spring.datasource.username=postgres
spring.datasource.password=1304
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:liquibase/db.changelog-master.xml
logging.level.root=info
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
sms.api.key=5e07d5bec3c4661fc130752bf4690ff2
sms.url=https://mainsms.ru/api/mainsms/message/send
sms.project.name=price-monitoring-sender